

haproxy:
  build: haproxy
  links:
    - consul
  ports:
    - "80:80"
    - "1936:1936"

consul:
  command: -server -bootstrap -advertise ROUTABLE_IP
  build: consul
  links:
    - pushgateway
  ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "consul/config:/etc/consul"
    - "consul/handlers:/handlers"

registrator:
  command: consul://consul:8500
  image: progrium/registrator:latest
  links:
    - consul
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"

prometheus:
  build: prometheus
  links:
    - pushgateway
    - haproxyexporter
  ports:
    - "9090:9090"
  volumes:
    - "prometheus/config:/config"

pushgateway:
  image: prom/pushgateway:latest
  ports:
  - "9091:9091"

haproxyexporter:
  command: -haproxy.scrape-uri=http://haproxy:1936/;csv
  image: prom/haproxy-exporter:latest
  links:
    - haproxy

elasticsearch:
  build: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - /opt/vision/elasticsearch/lib:/var/lib/elasticsearch
    - /opt/vision/elasticsearch/log:/var/log/supervisor
  hostname: elasticsearch

influxdb:
  build: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
    - "8099:8099"
  volumes:
    - /opt/vision/influxdb/lib:/var/lib/influxdb
    - /opt/vision/influxdb/log:/var/log/supervisor

grafana:
  build: grafana
  ports:
    - "9090:80"
  volumes:
    - /opt/vision/grafana/log:/var/log/supervisor
  links:
    - elasticsearch:elasticsearch
    - influxdb:influxdb

kibana:
  build: kibana
  ports:
    - "5601:5601"
  volumes:
    - /opt/vision/kibana/log:/var/log/supervisor
  links:
    - elasticsearch:elasticsearch

fluentd:
  build: fluentd
  ports:
    - "24224:24224"
    - "9292:9292"
  volumes:
    - /opt/vision/fluentd/log:/var/log/supervisor
  links:
    - elasticsearch:elasticsearch

cadvisor:
  image: google/cadvisor
  volumes:
   - /:/rootfs:ro
   - /var/run:/var/run:rw
   - /sys:/sys:ro
   - /var/lib/docker/:/var/lib/docker:ro
  ports:
   - "9999:8080"
