#
# Services
#

version: '2'

elasticsearch:
  image: portefaix/elasticsearch:2.2.0
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - /opt/vision/elasticsearch/data:/usr/share/elasticsearch/data
  log_driver: "syslog"

influxdb:
  image: portefaix/influxdb:0.11.0.1
  ports:
    - "8083:8083"
    - "8086:8086"
  volumes:
    - /opt/vision/influxdb/data:/var/lib/influxdb/data
  log_driver: "syslog"

grafana:
  image: portefaix/grafana:2.6.0
  ports:
    - "9191:3000"
  volumes:
    - /opt/vision/grafana/lib:/var/lib/grafana
    - /opt/vision/grafana/log:/var/log/grafana
  log_driver: "syslog"

kibana:
  image: portefaix/kibana:4.3.0
  ports:
    - "9393:5601"
  log_driver: "syslog"

heka:
  image: portefaix/heka:0.10.0b2
  ports:
    - "4881:4881"
    - "4352:4352"
  log_driver: "syslog"

cadvisor:
  image: google/cadvisor:v0.22.0
  command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
  ports:
    - "9090:8080"
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  links:
    - influxdb:influxdb
