#
# Services
#

elasticsearch:
  image: portefaix/elasticsearch:2.2.0
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - /opt/vision/elasticsearch/data:/usr/share/elasticsearch/data
  log_driver: "syslog"

influxdb:
  image: portefaix/influxdb:0.9.5
  ports:
    - "8083:8083"
    - "8086:8086"
  volumes:
    - /opt/vision/influxdb/lib:/var/lib/influxdb
  log_driver: "syslog"

grafana:
  image: portefaix/grafana:2.5.0
  ports:
    - "9191:3000"
  volumes:
    - /opt/vision/grafana/lib:/var/lib/grafana
    - /opt/vision/grafana/log:/var/log/grafana
  links:
    - influxdb:influxdb
  log_driver: "syslog"

kibana:
  image: portefaix/kibana:4.3.0
  ports:
    - "9393:5601"
  links:
    - elasticsearch
  log_driver: "syslog"

heka:
  image: portefaix/heka:0.10.0b2
  ports:
    - "4881:4881"
    - "4352:4352"
  log_driver: "syslog"
