[hekad]
maxprocs=10

#
# Input
# -------------------------------

[LogstreamerInput]
log_directory = "/var/log"
file_match = 'local7\.log'

[DockerLogInput]
## Default Docker endpoint
endpoint = "unix:///var/run/docker.sock"

#
# Encoder
# -------------------------------

[PayloadEncoder]
append_newlines = false

[ESJsonEncoder]
index = "%{Type}-%{2006.01.02}"
es_index_from_timestamp = true
type_name = "%{Type}"

#
# Output
# -------------------------------

[LogOutput]
message_matcher = "TRUE"
encoder = "PayloadEncoder"

[ElasticSearchOutput]
message_matcher = "TRUE"
server = "http://%ENV[ES_HOST]:%ENV[ES_PORT]"
flush_interval = 5000
flush_count = 10
encoder = "ESJsonEncoder"

#
# Misc
# -------------------------------

# Heka Dashboard for internal metrics and time series graphs
[Dashboard]
type = "DashboardOutput"
address = ":4352"
ticker_interval = 30
