# VERSION 1.5
# AUTHOR:         Nicolas Lamirault <nicolas.lamirault@gmail.com>
# DESCRIPTION:    vision/elasticsearch

FROM portefaix/elasticsearch:2.0.0
MAINTAINER Nicolas Lamirault <nicolas.lamirault@gmail.com>

RUN elasticsearch plugin install license
RUN elasticsearch plugin install marvel-agent
